#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ."
  bin = "./chirpy"
  delay = 500
  include_ext = ["go", "html"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  stop_on_error = true
  log = "build-errors.log"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[misc]
  clean_on_exit = false